### PR TITLE
change to WD and remove a few TODOs

### PR DESCRIPTION
**Pull request by mmpcn**

### CODE REVIEW

**Review by msdemlei — DISMISSED** [review]
Agree on removing the TODOs (although I *would* have liked to reference the XSAMS->HTML stylesheet they once had...).

However, I'd update the document date together with changing the document type lest it gets forgotten.

**Review by msdemlei — APPROVED** [review]
Thanks...

**Review by msdemlei — APPROVED** [review]
(Not sure why my previous review was not good enough for github).

I'm fine with all of this.

Looking again, I think you'd have to give me write access to make my reviews count.  Hm.  We'll have to think a bit more on the default config of ivoa repos.

**Review by jd-au — APPROVED** [review]
Approved, but removing a todo while leaving in the TBD seems strange.

**Comment by jd-au** [comment]
> (Not sure why my previous review was not good enough for github).
> 
> I'm fine with all of this.
> 
> Looking again, I think you'd have to give me write access to make my reviews count. Hm. We'll have to think a bit more on the default config of ivoa repos.

I've granted you write access - I don't think this is a default config issue, more just config for each repo to reflect the team working on it.

**Pull request merged**
